### ISSUE TITLE
Estrtutura das pastas.

### ISSUE THREAD

**Issue by fvieir** [CarolANikolic/thumbs-up#1]
Ola  Carol, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para estrtutura das pastas.

Segue uma ideia de como estruturar.

![image](https://user-images.githubusercontent.com/65264206/196414235-35e7d046-da1a-42d8-8206-bbc0b86641af.png)

Qualquer duvida é só chamar.

**Comment by CarolANikolic** [comment]
Oi Fabrício, tudo bem por aqui e com você?

Muito obrigada pelo seu valioso feedback! Já implementei sua sugestão e gostei do resultado. 
Por favor, sempre sinta-se a vontade para enviar suas ideias de melhorias.

Abraço!

**Comment by CarolANikolic** [comment]
Oi Fabrício, tudo bem por aqui e com você?

Muito obrigada pelo seu valioso feedback! Já implementei sua sugestão e gostei do resultado.
Por favor, sempre sinta-se a vontade para enviar suas ideias de melhorias.

Abraço!
